export const BLUE_MIND_COLORS = {
  primary: "#193B68",
  primaryHover: "#142F54",
  success: "#10B981",
  error: "#DC2626",
  warning: "#EA580C",
  info: "#0284C7",
  darkBackground: "#000000",
  lightBackground: "#FAFBFC",
  darkSidebar: "#000000",
  lightSidebar: "#FAFBFC",
  darkCard: "#000000",
  lightCard: "#FFFFFF",
  darkCardElevated: "#000000",
  lightCardElevated: "#F8FAFC",
  darkBorder: "rgba(255,255,255,0.10)",
  lightBorder: "#E5E7EB",
  darkBorderStrong: "rgba(255,255,255,0.18)",
  lightBorderStrong: "#CBD5E1",
  darkTextPrimary: "#FFFFFF",
  lightTextPrimary: "#111827",
  darkTextSecondary: "#E8E8E8",
  lightTextSecondary: "#64748B",
  darkTextMuted: "#B8B8B8",
  lightTextMuted: "#94A3B8",
  darkInput: "#000000",
  lightInput: "#FFFFFF",
  darkModal: "#000000",
  lightModal: "#FFFFFF",
  darkHover: "rgba(255,255,255,0.08)",
  lightHover: "rgba(25,59,104,0.07)",
  darkActive: "rgba(255,255,255,0.12)",
  lightActive: "#EEF2FF",
  darkDisabled: "#4B5563",
  lightDisabled: "#9CA3AF",
};

export const BLUE_MIND_CSS_VARS = {
  primary: "var(--bm-primary)",
  primaryHover: "var(--bm-primary-hover)",
  success: "var(--bm-success)",
  error: "var(--bm-error)",
  warning: "var(--bm-warning)",
  appBackground: "var(--bm-bg-app)",
  sidebarBackground: "var(--bm-bg-sidebar)",
  cardBackground: "var(--bm-bg-card)",
  elevatedBackground: "var(--bm-bg-elevated)",
  inputBackground: "var(--bm-bg-input)",
  modalBackground: "var(--bm-bg-modal)",
  border: "var(--bm-border)",
  borderStrong: "var(--bm-border-strong)",
  textPrimary: "var(--bm-text-primary)",
  textSecondary: "var(--bm-text-secondary)",
  textMuted: "var(--bm-text-muted)",
  hoverBackground: "var(--bm-hover-bg)",
  activeBackground: "var(--bm-active-bg)",
  disabledBackground: "var(--bm-disabled-bg)",
};

export const COLOR_OPTIONS = [
  { label: "Blue", value: "#193B68" },
  { label: "Sky", value: "#0284C7" },
  { label: "Cyan", value: "#0891B2" },
  { label: "Teal", value: "#0F766E" },
  { label: "Emerald", value: "#059669" },
  { label: "Green", value: "#16A34A" },
  { label: "Lime", value: "#65A30D" },
  { label: "Yellow", value: "#CA8A04" },
  { label: "Amber", value: "#D97706" },
  { label: "Orange", value: "#EA580C" },
  { label: "Red", value: "#DC2626" },
  { label: "Rose", value: "#E11D48" },
  { label: "Pink", value: "#DB2777" },
  { label: "Fuchsia", value: "#C026D3" },
  { label: "Purple", value: "#9333EA" },
  { label: "Violet", value: "#7C3AED" },
  { label: "Indigo", value: "#4F46E5" },
  { label: "Slate", value: "#475569" },
  { label: "Stone", value: "#57534E" },
  { label: "Zinc", value: "#52525B" },
  { label: "Mint", value: "#10B981" },
  { label: "Ocean", value: "#2563EB" },
  { label: "Berry", value: "#BE123C" },
  { label: "Copper", value: "#B45309" },
];

export const AVATAR_COLORS = [
  "#193B68",
  "#2563EB",
  "#059669",
  "#EA580C",
  "#DC2626",
  "#7C3AED",
  "#0891B2",
  "#BE123C",
];

export const SEARCH_ARTWORK_COLORS = [
  { from: "#193B68", via: "#3D7EC8", to: "#B9D7F6" },
  { from: "#0E7490", via: "#67E8F9", to: "#CFFAFE" },
  { from: "#6B5DD3", via: "#9C8CFF", to: "#E6DFFF" },
  { from: "#0F766E", via: "#34C3AA", to: "#C8F7EC" },
  { from: "#A855F7", via: "#D18BFF", to: "#F1D9FF" },
  { from: "#EA580C", via: "#FDBA74", to: "#FFEDD5" },
  { from: "#BE123C", via: "#FB7185", to: "#FFE4E6" },
  { from: "#1D4ED8", via: "#60A5FA", to: "#DBEAFE" },
];

export const WRITE_EDIT_ARTWORK_COLORS = {
  writing: { category: "Writing", from: "#3767D8", via: "#75A7FF", to: "#D8E8FF", accent: "#FFFFFF" },
  careerBlue: { category: "Career", from: "#193B68", via: "#3D7EC8", to: "#B9D7F6", accent: "#FFFFFF" },
  study: { category: "Study", from: "#6B5DD3", via: "#9C8CFF", to: "#E6DFFF", accent: "#FFFFFF" },
  business: { category: "Business", from: "#0F766E", via: "#34C3AA", to: "#C8F7EC", accent: "#FFFFFF" },
  careerPurple: { category: "Career", from: "#A855F7", via: "#D18BFF", to: "#F1D9FF", accent: "#FFFFFF" },
  social: { category: "Social", from: "#EA580C", via: "#FDBA74", to: "#FFEDD5", accent: "#FFFFFF" },
  product: { category: "Product", from: "#BE123C", via: "#FB7185", to: "#FFE4E6", accent: "#FFFFFF" },
};
